  - name: Make sure the lastest version is installed for minimal packages (mlocate, gpgme, sudo, man, openssh, wget, bzip2)
    apt: name={{ item }} state=present
    with_items:

      # utility to find files anywhere in the filesystem based on their name by using a previously created database to perform the search
      - mlocate

      # utility for retrieving files using the HTTP or FTP protocols
      - wget

      # file compression utility
      - bzip2

      # IT common
      - git
      - htop
      - logrotate
      - nmap
      - ntp
      - python-boto
      - telnet
      - vim
      - zabbix-agent
      - zip
